//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTransfer
    {
        public int TransferId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> FromRoomId { get; set; }
        public Nullable<int> ToRoomId { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string Note { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
